import Head from "next/head";
import Document from "../components/Document/Document";
import styles from "../styles/Home.module.css";
import { GalleryTile, Slide } from "../components/Tile/GalleryTile/GalleryTile";
import Row from "../components/Row/Row";
import PageBreak from "../components/PageBreak/PageBreak";
import BannerTile from "../components/Tile/BannerTile/BannerTile";
import CompanyLogoSVG from "../svg/logo/CompanyLogo";
import IFrameTile from "../components/Tile/IFrameTile/IFrameTile";
import ImageTile from "../components/Tile/ImageTile/ImageTile";
import VideoTile from "../components/Tile/VideoTile/VideoTile";
import Section from "../components/Section/Section";
import { TextTile } from "../components/Tile/TextTile/TextTile";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Document>
        <Section id="text_tile_1">
          <Row>
            <BannerTile
              style={{
                fontSize: "2rem",
                fontWeight: "300",
                borderTop: "1px solid black !important",
                textAlign: "justify",
                borderRadius: "0px",
              }}
            >
              <b style={{ fontSize: "4.2rem" }}>
                <i>An entertainment company</i>
              </b>{" "}
              run by{" "}
              <b>
                <i>professional musicians and audio engineers</i>
              </b>{" "}
              where{" "}
              <mark style={{ padding: "0px 1rem" }}>customer satisfaction</mark>{" "}
              and{" "}
              <mark style={{ padding: "0px 1rem" }}>attention to detail</mark>{" "}
              is our <b>highest priority.</b>
            </BannerTile>
          </Row>
        </Section>
        <Section id="home_section">
          <Row>
            {/* <BannerTile
              id={styles.title_card}
              style={{
                backgroundColor: "black",
                display: "flex",
                alignItems: "center",
                gap: "2rem",
              }}
            >
              <CompanyLogoSVG height="4rem" width="4rem" fill="white" />
              <h1
                style={{
                  fontSize: "2rem",
                  fontWeight: "300",
                  color: "white",
                  textAlign: "center",
                  width: "100%",
                }}
              >
                Mic Check Entertainment
              </h1>
            </BannerTile> */}
          </Row>
          <Row>
            {/* {          <GalleryTile height="30rem" width="100%">
            <Slide src="/images/dj_kev_closeup_side.jpg" alt="photographer">
              <b style={{ fontSize: "2rem" }}>Who We Are</b>
              <br />
              An entertainment company run by professional musicians and audio
              engineers where customer satisfaction and attention to detail is
              our highest priority.
            </Slide>
            <Slide src="/images/happy_couple_peace.jpg" alt="photographer">
              <b style={{ fontSize: "2rem" }}>What We Do</b>
              <br />
              We offer a full Wedding and Event entertainment service including
              Lighting and Photo Booth options.
            </Slide>
          </GalleryTile>} */}
            <VideoTile
              src="/videos/DJReel.Horizontal.mp4"
              src_type="video/mp4"
              height="40rem"
              width="100%"
            />
          </Row>
          {/* <Row>
            <BannerTile style={{ border: "none" }}>
            <p>
              An entertainment company run by professional musicians and audio
              engineers where customer satisfaction and attention to detail is
              our highest priority.
            </p>
          </BannerTile>
          </Row> */}
        </Section>{" "}
        <Section id="home_subsection_1">
          <Row>
            <ImageTile src="/images/Culver Hotel-8.png" />
          </Row>
        </Section>
        <Section id="home_subsection_2">
          <Row>
            <ImageTile src="/images/LRphoto2-29.png" />
          </Row>
        </Section>
        <Section id="home_subsection_3">
          <Row>
            <ImageTile src="/images/Kev DJ Culver Hotel-28.png" />
          </Row>
        </Section>
        <PageBreak>Mixes</PageBreak>
        <Section id="mixes_section">
          <Row>
            <IFrameTile
              width="100%"
              height="120px"
              src="https://player-widget.mixcloud.com/widget/IFrameTile/?hide_cover=1&light=1&feed=%2Fkevluuinthestu%2F"
              attributes={{ frameBorder: "0" }}
            ></IFrameTile>
          </Row>
          <Row>
            <IFrameTile
              width="100%"
              height="120px"
              src="https://player-widget.mixcloud.com/widget/IFrameTile/?hide_cover=1&light=1&feed=%2Fkevluuinthestu%2Fdj-kev-luu-pop-dj-mix%2F"
              attributes={{ frameBorder: "0" }}
            ></IFrameTile>
          </Row>
          <Row>
            <IFrameTile
              width="100%"
              height="120px"
              src="https://player-widget.mixcloud.com/widget/IFrameTile/?hide_cover=1&light=1&feed=%2Fkevluuinthestu%2Fdj-kev-luu-afrobeat-dj-mix%2F"
              attributes={{ frameBorder: "0" }}
            ></IFrameTile>
          </Row>
          <Row>
            <IFrameTile
              width="100%"
              height="120px"
              src="https://player-widget.mixcloud.com/widget/IFrameTile/?hide_cover=1&light=1&feed=%2Fkevluuinthestu%2Fcanto-pop-dj-mix%2F"
              attributes={{ frameBorder: "0" }}
            ></IFrameTile>
          </Row>
        </Section>
        <PageBreak>Book</PageBreak>
        <Section id="book_section"></Section> <PageBreak>Jobs</PageBreak>
      </Document>
    </>
  );
}

type TextProps = {
  children: string;
  bold?: boolean;
};
function Text(props: TextProps) {
  return (
    <TextTile
      style={{
        backgroundColor: "transparent",
        color: "black",
        boxShadow: "none",
      }}
    >
      {props.children}
    </TextTile>
  );
}
